deploy_straivedemo:
  stage: deploy
  tags:
    - straivedemo6
  image: instrumentisto/rsync-ssh
  script:
    - chmod og= $ID_RSA
    - rsync -avz -e "ssh -i $ID_RSA -o StrictHostKeyChecking=no" --no-perms --no-times ./ $SERVER_USER@$SERVER_IP:/var/www/html/sm-analytics